// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdFuv5Vl27XSiStXKEIXNLw-New_65oDY',
    appId: '1:909386276354:web:252566fec06775639f911b',
    messagingSenderId: '909386276354',
    projectId: 'my-first-project-udemy-139a7',
    authDomain: 'my-first-project-udemy-139a7.firebaseapp.com',
    storageBucket: 'my-first-project-udemy-139a7.appspot.com',
    measurementId: 'G-V33LLBYVQR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjaACEWgSidGvO30YZMWlzdLt7-ffPQTw',
    appId: '1:909386276354:android:723c50009301c1539f911b',
    messagingSenderId: '909386276354',
    projectId: 'my-first-project-udemy-139a7',
    storageBucket: 'my-first-project-udemy-139a7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAC1oRQGTJrz4SyY3QEcQRFaNEaBR8oVQ4',
    appId: '1:909386276354:ios:a2e2533c529890919f911b',
    messagingSenderId: '909386276354',
    projectId: 'my-first-project-udemy-139a7',
    storageBucket: 'my-first-project-udemy-139a7.appspot.com',
    androidClientId: '909386276354-enc9db26oi0tonojofo23adpgdqvkcel.apps.googleusercontent.com',
    iosClientId: '909386276354-92fi5kf1nhsa98o6rd875me1goeg0r9g.apps.googleusercontent.com',
    iosBundleId: 'com.example.benefactorProject',
  );
}
